### ISSUE TITLE
Comic says "snatched" and never finishes processing.

### ISSUE THREAD

**Issue by CubeyGlyph** [linuxserver/docker-mylar3#19]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Comic should download, process, and be placed in appropriate directory

## Current Behavior

Comic is marked as snatched but is not placed into cache directory, stays in snatched status

## Steps to Reproduce

1. No steps to reproduce, just 

## Environment
**OS:** Linux (Docker)
**CPU architecture:** x86_64/arm32/arm64
**How docker service was installed:**

## Command used to create docker container (run/create/compose/screenshot)

Portainer install
<img width="1100" alt="Screen Shot 2021-12-30 at 1 42 04 PM" src="https://user-images.githubusercontent.com/82244912/147779672-83ffb348-1fdc-49b2-a8ad-65b35f310afb.png">

## Docker logs

```
29-Dec-2021 18:02:37 - INFO    :: mylar.searcher.3647 : SEARCH-QUEUE : Found Black's Myth (2021) #1 using DDL
29-Dec-2021 18:02:37 - INFO    :: mylar.parse_downloadresults.536 : SEARCH-QUEUE : Only one item discovered, changing queue length to accomodate: {'series': 'Black’s Myth #1', 'site': 'Download Now', 'year': '2021', 'issues': None, 'size': ' 87 MB', 'link': 'https://getcomics.info/links.php/dlwyFR9qhs28y6xsBQ3tk0qIFmjDhw6rzF48qshDEm4lPVmTYtFgxpLvwd/2CaGETeEgmmBayq2ELne0td6+CJ8gvPQ4jT5B9gpmJ47SwdvjKMM37zT1k2UjhYJUg2DMCFgUXlOeJOg773wNvJvbzDSXpIDGtV4xyIBduHFJPeQ5aBktyLbzIswepodIzT+y:R81PwIKW/GkvB5CnMIVOow=='} [<class 'dict'>]
29-Dec-2021 18:02:37 - INFO    :: mylar.searcher.3940 : SEARCH-QUEUE : Successfully snatched Blacks.Myth.#1.(2021) from DDL site. It is currently being queued to download in position 20
29-Dec-2021 18:02:37 - INFO    :: mylar.nzblog.755 : SEARCH-QUEUE : setting the nzbid for this download grabbed by DDL in the nzblog to : 195759
29-Dec-2021 18:02:37 - INFO    :: mylar.foundsearch.824 : SEARCH-QUEUE : [UPDATER] Updating status to snatched
29-Dec-2021 18:02:37 - INFO    :: mylar.foundsearch.926 : SEARCH-QUEUE : [UPDATER] Updated the status (Snatched) complete for Black's Myth Issue: 1
29-Dec-2021 18:02:38 - INFO    :: mylar.search_results.228 : ThreadPoolExecutor-0_0 : There are 0 results
29-Dec-2021 18:02:40 - INFO    :: mylar.search_results.228 : ThreadPoolExecutor-0_0 : There are 0 results
```

**Comment by barbequesauce** [comment]
Please open this in the Mylar3 project rather than the LSIO repo - https://github.com/mylar3/mylar3

**Comment by CubeyGlyph** [comment]
Per the mylar3 project:

> Firstly, - your version of Mylar that you're running is (as best as I can tell) about 3+ months old based on the traceback error in your logs. You need to update.
>You also can't run nightly and be on master - the two are exclusive. You're either running nightly and tied to the python3-dev branch, or you're on master. If you're running nightly via docker, then you need to make sure in your config.ini that you set the git_branch = python3-dev so that it can properly display/check things.

How frequently is this docker build expected to update?

**Comment by barbequesauce** [comment]
Depends which image you're running. The main image is tied to mylar's master branch, which gets updated when we feel dev is stable - we aim for once every two weeks, but that is highly variable depending on what we are working on. The nightly image updates within 15 minutes of a commit to the mylar python3-dev branch...

**Comment by CubeyGlyph** [comment]
> Depends which image you're running. The main image is tied to mylar's master branch, which gets updated when we feel dev is stable - we aim for once every two weeks, but that is highly variable depending on what we are working on. The nightly image updates within 15 minutes of a commit to the mylar python3-dev branch...

Here is the one I am running.
```
"Hostname": "c19a8fcebc36",
        "Image": "linuxserver/mylar3:nightly-version-a36c5bcf",
        "Labels": {
            "build_version": "Linuxserver.io version:- a36c5bcf-ls134 Build-date:- 2021-09-30T21:21:53+02:00",
            "maintainer": "aptalca",
            "org.opencontainers.image.authors": "linuxserver.io",
            "org.opencontainers.image.created": "2021-09-30T21:21:53+02:00",
            "org.opencontainers.image.description": "[Mylar3](https://github.com/mylar3/mylar3) is an automated Comic Book downloader (cbr/cbz) for use with NZB and torrents written in python. It supports SABnzbd, NZBGET, and many torrent clients in addition to DDL.",
            "org.opencontainers.image.documentation": "https://docs.linuxserver.io/images/docker-mylar3",
            "org.opencontainers.image.licenses": "GPL-3.0-only",
            "org.opencontainers.image.ref.name": "51ed0a405e290e47b16144206ef0624a91efadb4",
            "org.opencontainers.image.revision": "51ed0a405e290e47b16144206ef0624a91efadb4",
            "org.opencontainers.image.source": "https://github.com/linuxserver/docker-mylar3",
            "org.opencontainers.image.title": "Mylar3",
            "org.opencontainers.image.url": "https://github.com/linuxserver/docker-mylar3/packages",
            "org.opencontainers.image.vendor": "linuxserver.io",
            "org.opencontainers.image.version": "a36c5bcf-ls134"
        },
        "OnBuild": null,
        "OpenStdin": false,
        "StdinOnce": false,
        "Tty": false,
        "User": "",
        "Volumes": {
            "/comics": {},
            "/config": {},
            "/downloads": {}
        },
```

**Comment by aptalca** [comment]
`"Image": "linuxserver/mylar3:nightly-version-a36c5bcf"`

You pinned the version in the docker tag, so you're not getting any updates

**Comment by aptalca** [comment]
You need to  use `linuxserver/mylar3:latest` or `linuxserver/mylar3:nightly` to create the container instead of `linuxserver/mylar3:nightly-version-a36c5bcf`

**Comment by barbequesauce** [comment]
Closed.
