### ISSUE TITLE
Pillow fails to install with webp support

### ISSUE THREAD

**Issue by chelming** [linuxserver/docker-mylar3#20]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Expect webp image conversions/parsing to work.

Exec-ing into the container, running python3 and the following should print out webp:
```python
>>> from PIL import features
>>> features.get_supported()
['pil', 'webp', 'webp_anim', 'webp_mux', 'transp_webp', 'libjpeg_turbo', 'jpg', 'zlib']

```

## Current Behavior
WebP parsing fails.
```python
>>> from PIL import features
>>> feautres.get_supported()
['pil', 'libjpeg_turbo', 'jpg', 'zlib']
```

## Steps to Reproduce
```shell
docker exec -it mylar bash
python3
from PIL import features
features.get_supported()
```

## Environment
**OS:** Ubuntu
**CPU architecture:** x86_64
**How docker service was installed:** apt

## Command used to create docker container (run/create/compose/screenshot)
docker build .
docker run -it 1596 bash

## Other
Interestingly if I pip uninstall Pillow && pip install Pillow, it installs with webp support. I'm thinking there's something going on at the time of the pip install that it's not seeing the webp libraries?

**Comment by chelming** [comment]
this patch fixes it. it appears that `--find-links` when installing requirements.txt is causing Pillow to not install correctly.
```patch
diff --git a/Dockerfile b/Dockerfile
index 9882f10..c59dcc3 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -41,6 +41,7 @@ RUN \
   tar xf /tmp/mylar3.tar.gz -C \
     /app/mylar3/ --strip-components=1 && \
   cd /app/mylar3 && \
+  pip install --no-cache-dir Pillow && \
   pip install --no-cache-dir --find-links https://wheel-index.linuxserver.io/alpine/ -r requirements.txt && \
   rm -rf lib/pathlib.py && \
   echo "**** cleanup ****" && \
   ```

**Comment by chelming** [comment]
sorry to keep spamming. since the precompiled wheel for Pillow doesn't have webp support I think the options are:

- Install Pillow before requirements.txt so it builds itself
- Remove `--find-links` from the pip install
- Get the Pillow wheel compiled with webp support

The second option seems like it'd add an excessive amount lot of time when building the container and I have no idea how to go about fixing an upstream wheel from alpine.

**Comment by aptalca** [comment]
I'm not familiar with pillow at all, but I do have this one question. If pillow is built with the optional dependency of webp, does it always require the webp package installed?

In other words, if I were to add the webp packages to our wheel builder so pillow builds with webp support, would I have to PR all the other images that use pillow to add the webp package?

I'm trying to figure out the easiest way to solve this.

Thanks

**Comment by chelming** [comment]
I think it'd be ok?

I tested in the mylar container with the above patch:
```shell
root@7fa92c6e12cd:/# python3
Python 3.9.5 (default, Nov 24 2021, 21:19:13)
[GCC 10.3.1 20210424] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from PIL import features
>>> features.get_supported()
['pil', 'webp', 'webp_anim', 'webp_mux', 'transp_webp', 'libjpeg_turbo', 'jpg', 'zlib']
>>> exit()

root@7fa92c6e12cd:/# apk del libwebp-tools
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.14/main: No such file or directory
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.14/community: No such file or directory
(1/4) Purging libwebp-tools (1.2.0-r2)
(2/4) Purging libwebp (1.2.0-r2)
(3/4) Purging giflib (5.2.1-r0)
(4/4) Purging libpng (1.6.37-r1)
Executing busybox-1.33.1-r6.trigger
OK: 125 MiB in 75 packages

root@7fa92c6e12cd:/# python3
Python 3.9.5 (default, Nov 24 2021, 21:19:13)
[GCC 10.3.1 20210424] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from PIL import features
>>> features.get_supported()
['pil', 'libjpeg_turbo', 'jpg', 'zlib']
>>>
```
it appears that if libwep-tools is missing from the runtime environment (even though it was compiled with it) then it just doesn't "have" that feature.

**Comment by aptalca** [comment]
That's good to know. Thanks for testing. I'll add it to build deps.

We had that issue with numpy. After we built numpy with support for blas (optional dep), it required blas runtime and broke a bunch of images.
