### ISSUE TITLE
sqlite3.IntegrityError: UNIQUE constraint failed: provider_searches.id

### ISSUE THREAD

**Issue by shredness** [linuxserver/docker-mylar3#23]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Normal Mylar3 functionality

## Current Behavior
503 Service Unavailable

## Steps to Reproduce

1. Pull latest mylar3 image (not nightly, but occurs with nightly as well) in Portainer
[_pull.savo.us_logs.txt](https://github.com/linuxserver/docker-mylar3/files/8261693/_pull.savo.us_logs.txt)

## Environment
**OS:**
**CPU architecture:** x86_64/arm32/arm64
**How docker service was installed:**

**Comment by tobbenb** [comment]
Please fill in all information in the issue template.

**Comment by barbequesauce** [comment]
Upstream issue corrected & ticket closed.
