### ISSUE TITLE
[BUG] Can't enable HTTPS, missing package `pyOpenSSL`

### ISSUE THREAD

**Issue by FirelightFlagboy** [linuxserver/docker-mylar3#28]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I can't enable HTTPS because `mylar3` can't find the module `pyOpenSSL` in the container 

### Expected Behavior

I would expected that the container to provide / `mylar3` to find `pyOpenSSL` python package

### Steps To Reproduce

1. Use the provided docker compose example
2. Go to the webui -> settings -> web interface 
3. Check `enable HTTPS` + configure TLS certificate & key
4. Restart the container / stack
5. Try to connect using the `https` protocol
    > though the `http` protocol still work 

### Environment

```markdown
- OS: Ubuntu 20.04
- How docker service was installed: `docker-ce@20.10.22` installed from docker APT repository
```

### CPU architecture

x86-64

### Docker creation

```bash
---
version: "3.9"
services:
  mylar3:
    image: linuxserver/mylar3:0.7.0
    environment:
      PUID: "1000"
      PGID: "1000"
    volumes:
      - /path/to/data:/config
      - /path/to/comics:/comics
      - /path/to/downloads:/downloads
    ports:
      - 8090:8090
    restart: unless-stopped
```

### Container logs

```txt
31-Dec-2022 10:47:05 - WARNING :: mylar.main.428 : MAIN : The pyOpenSSL module is missing. Install this module to enable HTTPS. HTTPS will be disabled.
31-Dec-2022 10:47:05 - INFO :: mylar.initialize.73 : MAIN : Starting Mylar on http://0.0.0.0:8090/
```

**Comment by FirelightFlagboy** [comment]
Can this be un-staled ?

**Comment by aptalca** [comment]
We install everything in their requirements. Also, instead of enabling https in the app, we recommend reverse proxying. SWAG is our homegrown nginx basewd reverse proxy with a preset proxy conf for mylar: https://github.com/linuxserver/docker-swag

If you really want to enable https, you can try installing the module via https://github.com/linuxserver/docker-mods/tree/universal-package-install

**Comment by FirelightFlagboy** [comment]
Ok, the reverse proxy was my current workaround.

That's right `mylar` don't list `pyOpenSSL` as a dependency for the project.

https://github.com/mylar3/mylar3/blob/5c1b5e25c60cfad751f55bdba82d2234bcb80be6/requirements.txt

I would probably open an issue on their repo for the missing dependencies.

Anyway, I will close this issue then
