### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by MaartenMol** [linuxserver/docker-mylar3#35]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

<html>
<body>

2023/07/21 12:58:01 | stdout | ModuleNotFoundError: No module named 'requests'
-- | -- | --
2023/07/21 12:58:01 | stdout | import requests
2023/07/21 12:58:01 | stdout | File "/app/mylar3/mylar/__init__.py", line 27, in <module>
2023/07/21 12:58:01 | stdout | import mylar
2023/07/21 12:58:01 | stdout | File "/app/mylar3/Mylar.py", line 27, in <module>
2023/07/21 12:58:01 | stdout | Traceback (most recent call last):

</body>
</html>

### Steps To Reproduce

Start container with the current latest docker image

### Environment

```markdown
- OS:
- How docker service was installed:
Docker on Synology
```

### CPU architecture

x86-64

### Docker creation

```bash
Synology GUI
```

### Container logs

```bash
2023/07/21 12:58:01	stdout	ModuleNotFoundError: No module named 'requests'
2023/07/21 12:58:01	stdout	    import requests
2023/07/21 12:58:01	stdout	  File "/app/mylar3/mylar/__init__.py", line 27, in <module>
2023/07/21 12:58:01	stdout	    import mylar
2023/07/21 12:58:01	stdout	  File "/app/mylar3/Mylar.py", line 27, in <module>
2023/07/21 12:58:01	stdout	Traceback (most recent call last):
```

**Comment by Roxedus** [comment]
This is Synologys bug. https://info.linuxserver.io/issues/2023-05-22-portainer/

**Comment by infomofo** [comment]
I am encountering this issue as well- I am not using synology but I am using portainer.

**Comment by bill-roemhild** [comment]
Quick fix for venv not being used on launch.

Subject: [PATCH] This is to fix venv not being used.
---
Index: root/etc/s6-overlay/s6-rc.d/svc-mylar3/run
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/root/etc/s6-overlay/s6-rc.d/svc-mylar3/run b/root/etc/s6-overlay/s6-rc.d/svc-mylar3/run
--- a/root/etc/s6-overlay/s6-rc.d/svc-mylar3/run	(revision 7235b82968ae30f70d3f4eb37f1e264aa8470bac)
+++ b/root/etc/s6-overlay/s6-rc.d/svc-mylar3/run	(date 1694965881127)
@@ -3,5 +3,5 @@
 
 exec \
     s6-notifyoncheck  -d -n 300 -w 1000 -c "nc -z localhost 8090" \
-        s6-setuidgid abc python3 /app/mylar3/Mylar.py --nolaunch \
+        s6-setuidgid abc /lsiopy/bin/python3.11 /app/mylar3/Mylar.py --nolaunch \
         --datadir /config/mylar

**Comment by bill-roemhild** [comment]
Subject: [PATCH] This is to fix venv not being used.
```
---
Index: root/etc/s6-overlay/s6-rc.d/svc-mylar3/run
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/root/etc/s6-overlay/s6-rc.d/svc-mylar3/run b/root/etc/s6-overlay/s6-rc.d/svc-mylar3/run
--- a/root/etc/s6-overlay/s6-rc.d/svc-mylar3/run	(revision 7235b82968ae30f70d3f4eb37f1e264aa8470bac)
+++ b/root/etc/s6-overlay/s6-rc.d/svc-mylar3/run	(date 1694965881127)
@@ -3,5 +3,5 @@
 
 exec \
     s6-notifyoncheck  -d -n 300 -w 1000 -c "nc -z localhost 8090" \
-        s6-setuidgid abc python3 /app/mylar3/Mylar.py --nolaunch \
+        s6-setuidgid abc /lsiopy/bin/python3.11 /app/mylar3/Mylar.py --nolaunch \
         --datadir /config/mylar

```

**Comment by aptalca** [comment]
That is not a proper fix, but more of a bandaid. The proper fix is included in the link above
